language: node_js

node_js:
  - 4.5.0

install:
  - npm install

services: 
  - mongodb

script:
  - ./test/install.sh && npm run cover

env:
#  - TEST_USERNAME=test
#  - TEST_PASSWORD=testpass

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

notifications:
  slack: pestillilab:aoYIQOothA5mB6fYrw3802Zj
